#ifndef BOARD_CONFIG_H_
#define BOARD_CONFIG_H_

#include <driver/gpio.h>

// Audio rate
#define AUDIO_INPUT_REFERENCE true
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// Enable Simplex (two bus systems)
#define AUDIO_I2S_METHOD_SIMPLEX

// Speaker (TX, MASTER) - Bus #0
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_4
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_2

// Microphone (RX, MASTER) - Bus #1 (SCK diubah ke GPIO 15)
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_15
#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_9
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_1

// TFT Display SPI (128x160)
#define DISPLAY_SPI_HOST SPI2_HOST
#define DISPLAY_WIDTH  128
#define DISPLAY_HEIGHT 160

#define DISPLAY_PIN_MOSI GPIO_NUM_11
#define DISPLAY_PIN_SCLK GPIO_NUM_12
#define DISPLAY_PIN_CS   GPIO_NUM_10
#define DISPLAY_PIN_DC   GPIO_NUM_13
#define DISPLAY_PIN_RST  GPIO_NUM_14
#define DISPLAY_PIN_BCKL GPIO_NUM_21

#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  false

#define DISPLAY_RGB_ORDER LCD_RGB_ORDER_BGR

// Onboard LED
#define BUILTIN_LED_GPIO GPIO_NUM_48

// Buttons
#define BOOT_BUTTON_GPIO GPIO_NUM_0         // Tombol Boot
#define VOLUME_UP_BUTTON_GPIO GPIO_NUM_3    // Tombol Volume Atas
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_8  // Tombol Volume Bawah

#define TOUCH_BUTTON_GPIO GPIO_NUM_3

#endif  // BOARD_CONFIG_H_
