name: Build ESP32 Firmware

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1.2

      - name: Build Firmware
        run: |
          idf.py build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: build/*.bin
